apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.paybill.secret.name | default "paybill" }}
  labels:
    {{- include "paybill.labels" . | nindent 4 }}
    {{- include "paybill.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.external_postgresql.enabled }}
  PG_HOST: {{ include "paybill.postgresql.host" . | b64enc | quote }}
  PG_PORT: {{ include "paybill.postgresql.port" . | b64enc | quote }}
  PG_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  PG_PASS: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  PG_HOST: {{ .Values.external_postgresql.PG_HOST | b64enc | quote }}
  PG_PORT: {{ .Values.external_postgresql.PG_PORT | b64enc | quote }}
  PG_USER: {{ .Values.external_postgresql.PG_USER | b64enc | quote }}
  PG_PASS: {{ .Values.external_postgresql.PG_PASS | b64enc | quote }}
  {{- end }}
  PG_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  APP_KEY: {{ .Values.apps.paybill.secret.data.app_key | b64enc | quote }}
  {{- if .Values.paybilldb_external_postgresql.enabled }}
  PB_DB_HOST: {{ .Values.paybilldb_external_postgresql.PB_DB_HOST | b64enc | quote }}
  PB_DB_USER: {{ .Values.paybilldb_external_postgresql.PB_DB_USER | b64enc | quote }}
  PB_DB_PASS: {{ .Values.paybilldb_external_postgresql.PB_DB_PASS | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paybill.fullname" . }}-redis
  labels:
    {{- include "paybill.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.auth.enabled }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}