apiVersion: v1
kind: Service
metadata:
  name: {{ include "paybill.fullname" . }}
  labels:
    {{- include "paybill.labels" . | nindent 4 }}
    {{- include "paybill.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apps.paybill.service.type }}
  ports:
    - port: {{ .Values.apps.paybill.service.port }}
      targetPort: {{ .Values.apps.paybill.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "paybill.selectorLabels" . | nindent 4 }}