apiVersion: v1
kind: Service
metadata:
  name: paybill
spec:
  type: LoadBalancer
  selector:
    component: paybill
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https